# Generated by Django 4.1.4 on 2022-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(default="None", max_length=200)),
                ("comment", models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(default=None, max_length=200)),
                ("from_time", models.CharField(default=None, max_length=200)),
                ("to_time", models.CharField(default=None, max_length=200)),
                ("account", models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=200)),
                ("status", models.CharField(default="off", max_length=200)),
            ],
        ),
    ]
