# Generated by Django 4.1.4 on 2022-12-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="user_email",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
