# Generated by Django 4.1.4 on 2023-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insta", "0004_time_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=None, max_length=200)),
                ("insta_id", models.CharField(default=None, max_length=200)),
                ("insta_pass", models.CharField(default=None, max_length=200)),
                ("status", models.CharField(default="off", max_length=200)),
            ],
        ),
    ]
